environment:
  observation_space_size: 5
  action_space_range: 2  # Number of possible actions the agent can take in the environment
training:
  number_of_workers: 16  # Number of parallel processes to use for training.
  number_of_env_per_worker: 1  # Number of training environments simulated by each worker process.
  training_iterations: 100  # Total number of training iterations (over a) to perform.
  training_batch_size: 4000 # Total amount of environment steps taken during each training iteration