name: Ruff

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: pip install ruff
    - run: ruff check core --verbose --output-format-github
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install mypy
      - run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context