name: Ruff

on: push

jobs:
  call-python-setup:
    uses: ./.github/workflows/python-setup.yaml
  ruff:
    runs-on: ubuntu-latest
    needs: call-python-setup
    steps:
    - run: ruff check core --verbose --output-format=github
  mypy:
    runs-on: ubuntu-latest
    needs: call-python-setup
    steps:
      - run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context