name: linters

on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: ruff
      run: ruff check core --verbose --output-format=github

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: 'core/requirements.txt'
      - run: pip install -r core/requirements.txt
      - name: mypy
        run: mypy core --show-error-codes --pretty --show-column-numbers --show-error-context
