name: python-setup
on:
  workflow_call:

jobs:
  python-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - run: pip install -r core/requirements.txt